name: example
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
    
  dynamic_widget: ^4.0.5
  dynamic_component: any

  flutter_staggered_grid_view: ^0.6.1
  extended_image: ^6.2.1
  faker_dart: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: any
  dynamic_component_codegen: any

dependency_overrides:
  dynamic_widget:
    git: 
      url: https://github.com/TshineZheng/dynamic_widget.git
      ref: qh
  dynamic_component:
    path: ../dynamic_component
  dynamic_component_codegen:
    path: ../codegen

flutter:
  uses-material-design: true
  assets:
    - assets/
