targets:
  $default:
    builders:
      dynamic_component_codegen:
        enabled: true

builders:
  dynamic_component_codegen:
    import: "package:dynamic_component_codegen/builder.dart"
    builder_factories: ["dynamicComponentCodegen"]
    build_extensions: {".dart": ["dynamic_component.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]